import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./stores/**/*.{js,ts,jsx,tsx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Midnight Obsidian design system ─────────────────────────────────
        "surface-tint":              "#c0c1ff",
        "inverse-on-surface":        "#313030",
        "primary-fixed":             "#e1e0ff",
        "on-tertiary":               "#2d2a5b",
        "on-surface-variant":        "#c7c4d7",
        "surface-container-lowest":  "#0e0e0e",
        "on-primary-fixed":          "#07006c",
        "on-surface":                "#e5e2e1",
        "surface-container-highest": "#353534",
        "on-error-container":        "#ffdad6",
        "secondary-fixed-dim":       "#b9c8de",
        "error":                     "#ffb4ab",
        "surface-container-low":     "#1c1b1b",
        "surface-dim":               "#131313",
        "primary":                   "#c0c1ff",
        "on-tertiary-fixed":         "#181445",
        "secondary-container":       "#39485a",
        "error-container":           "#93000a",
        "on-secondary":              "#233143",
        "on-background":             "#e5e2e1",
        "primary-container":         "#8083ff",
        "on-error":                  "#690005",
        "surface":                   "#131313",
        "tertiary-container":        "#8e8bc2",
        "primary-fixed-dim":         "#c0c1ff",
        "on-tertiary-fixed-variant": "#444173",
        "tertiary":                  "#c4c1fb",
        "surface-container-high":    "#2a2a2a",
        "on-secondary-fixed-variant":"#39485a",
        "on-tertiary-container":     "#262354",
        "outline-variant":           "#464554",
        "surface-bright":            "#3a3939",
        "inverse-primary":           "#494bd6",
        "on-secondary-fixed":        "#0d1c2d",
        "secondary":                 "#b9c8de",
        "surface-container":         "#201f1f",
        "secondary-fixed":           "#d4e4fa",
        "background":                "#131313",
        "tertiary-fixed":            "#e3dfff",
        "inverse-surface":           "#e5e2e1",
        "on-primary-fixed-variant":  "#2f2ebe",
        "on-primary":                "#1000a9",
        "outline":                   "#908fa0",
        "tertiary-fixed-dim":        "#c4c1fb",
        "surface-variant":           "#353534",
        "on-secondary-container":    "#a7b6cc",
        "on-primary-container":      "#0d0096",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      spacing: {
        "stack-sm":      "12px",
        "stack-md":      "24px",
        "stack-lg":      "48px",
        "container-max": "1200px",
        unit:            "4px",
        "margin-page":   "40px",
        gutter:          "24px",
        "reading-width": "680px",
      },
      fontFamily: {
        headline:      ["Newsreader", "Georgia", "serif"],
        body:          ["Newsreader", "Georgia", "serif"],
        label:         ["Manrope", "system-ui", "sans-serif"],
        "ui-main":     ["Manrope", "sans-serif"],
        "label-caps":  ["Manrope", "sans-serif"],
        "body-reading":["Newsreader", "serif"],
        "h2":          ["Newsreader", "serif"],
        "h1":          ["Newsreader", "serif"],
        "ui-sm":       ["Manrope", "sans-serif"],
      },
      fontSize: {
        "ui-main":     ["16px", { lineHeight: "24px",  letterSpacing: "0",     fontWeight: "500" }],
        "label-caps":  ["12px", { lineHeight: "16px",  letterSpacing: "0.1em", fontWeight: "700" }],
        "body-reading":["20px", { lineHeight: "1.6",   letterSpacing: "0.01em",fontWeight: "400" }],
        "h2":          ["32px", { lineHeight: "1.2",   letterSpacing: "-0.01em",fontWeight: "500" }],
        "h1":          ["48px", { lineHeight: "1.1",   letterSpacing: "-0.02em",fontWeight: "600" }],
        "ui-sm":       ["14px", { lineHeight: "20px",  letterSpacing: "0.02em",fontWeight: "600" }],
      },
      animation: {
        "highlight-pulse": "highlightPulse 0.3s ease-out",
        "fade-in":         "fadeIn 0.2s ease-out",
        "slide-up":        "slideUp 0.3s ease-out",
      },
      keyframes: {
        highlightPulse: {
          "0%":   { backgroundColor: "rgba(192, 193, 255, 0.3)" },
          "100%": { backgroundColor: "rgba(192, 193, 255, 0.1)" },
        },
        fadeIn:  { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp: {
          "0%":   { transform: "translateY(8px)", opacity: "0" },
          "100%": { transform: "translateY(0)",   opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
